apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notion-ical-sync-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: notion-sync.opendiy.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notion-ical-sync
            port:
              number: 80
